/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryRouteImport } from './routes/try'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TryImpactCardIdRouteImport } from './routes/try.impact.$cardId'

const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TryImpactCardIdRoute = TryImpactCardIdRouteImport.update({
  id: '/impact/$cardId',
  path: '/impact/$cardId',
  getParentRoute: () => TryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/try': typeof TryRouteWithChildren
  '/try/impact/$cardId': typeof TryImpactCardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/try': typeof TryRouteWithChildren
  '/try/impact/$cardId': typeof TryImpactCardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/try': typeof TryRouteWithChildren
  '/try/impact/$cardId': typeof TryImpactCardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/try' | '/try/impact/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/try' | '/try/impact/$cardId'
  id: '__root__' | '/' | '/try' | '/try/impact/$cardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TryRoute: typeof TryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try/impact/$cardId': {
      id: '/try/impact/$cardId'
      path: '/impact/$cardId'
      fullPath: '/try/impact/$cardId'
      preLoaderRoute: typeof TryImpactCardIdRouteImport
      parentRoute: typeof TryRoute
    }
  }
}

interface TryRouteChildren {
  TryImpactCardIdRoute: typeof TryImpactCardIdRoute
}

const TryRouteChildren: TryRouteChildren = {
  TryImpactCardIdRoute: TryImpactCardIdRoute,
}

const TryRouteWithChildren = TryRoute._addFileChildren(TryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TryRoute: TryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
