/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchNameRouteImport } from './routes/research.$name'
import { Route as ApiVerifyRouteImport } from './routes/api/verify'
import { Route as ApiResearchRouteImport } from './routes/api/research'

const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchNameRoute = ResearchNameRouteImport.update({
  id: '/research/$name',
  path: '/research/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyRoute = ApiVerifyRouteImport.update({
  id: '/api/verify',
  path: '/api/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/policies': typeof PoliciesRoute
  '/api/research': typeof ApiResearchRoute
  '/api/verify': typeof ApiVerifyRoute
  '/research/$name': typeof ResearchNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/policies': typeof PoliciesRoute
  '/api/research': typeof ApiResearchRoute
  '/api/verify': typeof ApiVerifyRoute
  '/research/$name': typeof ResearchNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/policies': typeof PoliciesRoute
  '/api/research': typeof ApiResearchRoute
  '/api/verify': typeof ApiVerifyRoute
  '/research/$name': typeof ResearchNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/policies'
    | '/api/research'
    | '/api/verify'
    | '/research/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/policies'
    | '/api/research'
    | '/api/verify'
    | '/research/$name'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/policies'
    | '/api/research'
    | '/api/verify'
    | '/research/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  PoliciesRoute: typeof PoliciesRoute
  ApiResearchRoute: typeof ApiResearchRoute
  ApiVerifyRoute: typeof ApiVerifyRoute
  ResearchNameRoute: typeof ResearchNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$name': {
      id: '/research/$name'
      path: '/research/$name'
      fullPath: '/research/$name'
      preLoaderRoute: typeof ResearchNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify': {
      id: '/api/verify'
      path: '/api/verify'
      fullPath: '/api/verify'
      preLoaderRoute: typeof ApiVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  PoliciesRoute: PoliciesRoute,
  ApiResearchRoute: ApiResearchRoute,
  ApiVerifyRoute: ApiVerifyRoute,
  ResearchNameRoute: ResearchNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
